### ISSUE TITLE
RMSE in Hz or not for Fig. 4?

### ISSUE THREAD

**Issue by JeffFessler** [ClaireYLin/regularized-field-map-estimation#5]
Fig. 4 in the paper shows RMSE labeled in Hz:
https://github.com/ClaireYLin/regularized-field-map-estimation/blob/1e60f83feb7baafd5d767e777f8fd68033488ea3/examples/example_simu_fieldmap.m#L126
but the data passed to `compute_rmsd` is all "w" arrays like `wtrue` in units of rad/s
https://github.com/ClaireYLin/regularized-field-map-estimation/blob/1e60f83feb7baafd5d767e777f8fd68033488ea3/examples/example_simu_fieldmap.m#L122
So perhaps the actual RMSE values are 2\pi lower than what is shown in Fig. 4, right?
Please just reply without changing code because I am in the middle of making several changes.

**Comment by JeffFessler** [comment]
A closely related question is what is the factor of `2` in this RMSD calculation:
https://github.com/ClaireYLin/regularized-field-map-estimation/blob/b8f0e7faec1fb5c6974bc9cd9caf946a6190d582/functions/compute_rmsd.m#L27
Was that supposed to be `2*pi`?  If so our graphs are probably off by `pi` not by `2pi`.

**Comment by ClaireYLin** [comment]
You are right - the input to `compute_rmsd` is `wtrue`, but the error should be divided by 2*pi instead of 2.
