### ISSUE TITLE
Wrong preconditioner for the non-preconditioned case

### ISSUE THREAD

**Issue by JeffFessler** [ClaireYLin/regularized-field-map-estimation#6]
For the simulated fieldmap case, the block of code that supposedly runs the non-preconditioned case here:
https://github.com/ClaireYLin/regularized-field-map-estimation/blob/070c803e922a8b424c80d615828b827aebc38669/examples/example_simu_fieldmap.m#L109
is actually deferring to the default precon which is `'ichol'` here:
https://github.com/ClaireYLin/regularized-field-map-estimation/blob/070c803e922a8b424c80d615828b827aebc38669/functions/fmap_est_pcg_ls.m#L54

I will fix this.

**Comment by ClaireYLin** [comment]
That is correct. I think what happened was I changed the default precon to `'ichol'` when I did the final cleanup for the GitHub upload..

**Comment by JeffFessler** [comment]
Closed by #9
